### ISSUE TITLE
Typo in android sdk build-tools

### ISSUE THREAD

**Issue by lmmsoft** [caipivara/awesome-android-scripts#2]
https://github.com/caipivara/awesome-android-scripts/blob/3408837b691411928f7e8c1146b102cd9ee7597d/install-android-dependencies.sh#L21

should be "build-tools;25.0.6"  rather than "buildDate-tools;25.0.6" ?

**Comment by danielgomezrico** [comment]
@lmmsoft thanks, now It's fixed on ^^
